javascript_compressor: uglifier
compress_assets: off
template_function: _.template
template_namespace: App.Templates

javascripts:
  common:
    - public/javascripts/libs/modernizr.js
    - public/javascripts/libs/jquery.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
  application:
    - public/javascripts/application.js
    - public/javascripts/routers/*.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/views/*.js
stylesheets:
  application:
    - public/stylesheets/*.css
